# -- Theme Options --
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showCopyright = true
  showAppearanceSwitcher = true
  showScrollToTop = true
  customText = "Made with ❤️ at Y Lab"

[homepage]
  layout = "background"
  showRecent = true
  showRecentItems = 6
  cardView = true

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  showTableOfContents = true
  showWordCount = true
  showComments = true
  sharingLinks = ["linkedin", "twitter", "whatsapp", "telegram", "email"]
